Special Character Removal 

In [107]:
import re 

#input string 
input_str = "Hello$ hoe# are@ yo!u"

#Using regular expression to revome the special character 
clean_str = re.sub(r"[^a-zA-Z0-9\s]", "",input_str)

print(clean_str)

Hello hoe are you


In [108]:
import re 

#input string 
input_str = "Hello$ ho2234e# are@ yo!u"

#Using regular expression to revome the special character 
clean_str = re.sub(r"[^a-zA-Z\s]", "",input_str)

print(clean_str)

Hello hoe are you


Libraries in the field of NLP 
1. spaCy - NLP libraries in the pyhon that can be used to tokenize and process texual data
2. nltk

In [109]:
import spacy

#load the spacy model 
nlp = spacy.load("en_core_web_sm")
#input String 
input_str = "Hello$ who# are@ yo!u" 

#Function to clean the data 
def clean_text(text): 
    clean_text = ''.join(char for char in text if char.isalpha() or char.isspace())
    doc = nlp(clean_text)
    return ' '.join(token.text for token in doc)

#Get the final output 
clean_str = clean_text(input_str)
print(clean_str)

Hello who are you


In [110]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\moham\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [111]:
import nltk
print(nltk.data.path)


['C:\\Users\\moham/nltk_data', 'C:\\Users\\moham\\anaconda3\\nltk_data', 'C:\\Users\\moham\\anaconda3\\share\\nltk_data', 'C:\\Users\\moham\\anaconda3\\lib\\nltk_data', 'C:\\Users\\moham\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']


In [112]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\moham\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [113]:
# from nltk.tokenize import word_tokenize
input_str = "Hello$ who# are@ yo!u"  
#Tokenize 
tokens = nltk.word_tokenize(input_str)

#Remove the special character 

clean_tokens = [token for token in tokens if token.isalnum() ]

clean_str = ' '.join(clean_tokens)
print(clean_str)

Hello who are yo u


Handle contractions

In [114]:
import contractions 
txt = "I can't brlieve it's already running" 
expanded_txt = contractions.fix(txt)
print(expanded_txt)

I cannot brlieve it is already running


In [115]:
import re

def expand_contractions(text): 
    contractions_pattern = {
        r"(?i)can't": "cannot",
        r"(?i)won't": "will not",
        r"(?i)it's": "it is",
        r"(?i)weren't": "were not",
        r"(?i)i'm": "i am"
    }

    for contraction, expansion in contractions_pattern.items(): 
        text = re.sub(contraction, expansion, text)
    
    return text

txt = "I can't brlieve it's already running" 
expanded_txt = expand_contractions(txt)
print(expanded_txt)


I cannot brlieve it is already running


Tokenization

In [116]:
import nltk 
from nltk.tokenize import word_tokenize, sent_tokenize 

#Sample text for tokenization 
txt = "NLTK provides powerful tools for tokenization. It include word tokenization and sentence tokenzation"
#Word tokenization 
words = word_tokenize(txt)
print(words)

['NLTK', 'provides', 'powerful', 'tools', 'for', 'tokenization', '.', 'It', 'include', 'word', 'tokenization', 'and', 'sentence', 'tokenzation']


In [117]:
#sentence tokenization 

sentance = sent_tokenize(txt)
print(sentance)

['NLTK provides powerful tools for tokenization.', 'It include word tokenization and sentence tokenzation']


Stop Words 

In [118]:
import nltk 
nltk.download('stopwords')

from nltk.corpus import stopwords 
from nltk.tokenize import sent_tokenize, word_tokenize

#Sample sentance 
sentence = "This is a sample sentence, showing of the stop words filterassion" 

#Tokenize the sentence 

words = word_tokenize(sentence) 

#Filter out stopwords 

new_sentence = [word for word in words if word.lower () not in stopwords.words('english')]  

print(sentence)
print(new_sentence)

This is a sample sentence, showing of the stop words filterassion
['sample', 'sentence', ',', 'showing', 'stop', 'words', 'filterassion']


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\moham\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


n - Grams

In [119]:
import nltk 
from nltk.tokenize import word_tokenize 
from nltk import ngrams 

def generate_ngrams(text, n):
    tokens = word_tokenize(txt)
    n_grams = list(ngrams(tokens, n))
    return n_grams
#Example text 
txt = "N grams are a sequence of n items for a given sample of text or speech"

unigrams = generate_ngrams(txt, 1)
bigrams = generate_ngrams(txt, 2) 
trigrams = generate_ngrams(txt, 3)



In [120]:
print(unigrams)

    

[('N',), ('grams',), ('are',), ('a',), ('sequence',), ('of',), ('n',), ('items',), ('for',), ('a',), ('given',), ('sample',), ('of',), ('text',), ('or',), ('speech',)]


In [121]:
print(bigrams)


[('N', 'grams'), ('grams', 'are'), ('are', 'a'), ('a', 'sequence'), ('sequence', 'of'), ('of', 'n'), ('n', 'items'), ('items', 'for'), ('for', 'a'), ('a', 'given'), ('given', 'sample'), ('sample', 'of'), ('of', 'text'), ('text', 'or'), ('or', 'speech')]


In [122]:
print(trigrams)

[('N', 'grams', 'are'), ('grams', 'are', 'a'), ('are', 'a', 'sequence'), ('a', 'sequence', 'of'), ('sequence', 'of', 'n'), ('of', 'n', 'items'), ('n', 'items', 'for'), ('items', 'for', 'a'), ('for', 'a', 'given'), ('a', 'given', 'sample'), ('given', 'sample', 'of'), ('sample', 'of', 'text'), ('of', 'text', 'or'), ('text', 'or', 'speech')]


Bag of Words

In [160]:
import numpy as np  
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [124]:
df = pd.read_csv('spam.csv', encoding='latin-1')
df.head()


v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [125]:
df.v1.value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [126]:
df.v1.value_counts()/len(df)*100

v1
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [127]:
df['spam'] = df['v1'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  spam  
0        NaN        NaN     0  
1        NaN        NaN     0  
2        NaN        NaN     1  
3        NaN        NaN     0  
4        NaN        NaN     0

In [128]:
df =df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)


In [129]:
df = df.rename(columns={'v2': 'message' , 'v1': 'Category'})

In [130]:
new_df = pd.read_csv('spam.csv', encoding='latin-1')

In [131]:
new_df['v1'].replace({'ham': 0, 'spam': 1}, inplace=True)

C:\Users\moham\AppData\Local\Temp\ipykernel_18712\2304353612.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['v1'].replace({'ham': 0, 'spam': 1}, inplace=True)
C:\Users\moham\AppData\Local\Temp\ipykernel_18712\2304353612.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df['v1'].rep

In [132]:
new_df.head()

v1                                                 v2 Unnamed: 2  \
0   0  Go until jurong point, crazy.. Available only ...        NaN   
1   0                      Ok lar... Joking wif u oni...        NaN   
2   1  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   0  U dun say so early hor... U c already then say...        NaN   
4   0  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [133]:
new_df =new_df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)


In [134]:
new_df

v1                                                 v2
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...
...   ..                                                ...
5567   1  This is the 2nd time we have tried 2 contact u...
5568   0              Will Ì_ b going to esplanade fr home?
5569   0  Pity, * was in mood for that. So...any other s...
5570   0  The guy did some bitching but I acted like i'd...
5571   0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [135]:
new_df = new_df.rename(columns={'v2': 'message','v1': 'Category'})

In [136]:
new_df.head()

Category                                            message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [137]:
df.head()

Category                                            message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [138]:
df.shape

(5572, 3)

In [139]:
#Train Test Split 
X_train, X_test, y_train, y_test = train_test_split(df.message, df.spam, test_size=0.2)

In [140]:
X_train.shape

(4457,)

In [141]:
X_test.shape

(1115,)

In [142]:
X_train[:4]

3730    Isn't frnd a necesity in life? imagine urself ...
4875    lyricalladie(21/F) is inviting you to be her f...
1247    Horrible gal. Me in sch doing some stuff. How ...
4553    Try to do something dear. You read something f...
Name: message, dtype: object

In [143]:
y_train[:4]

3730    0
4875    1
1247    0
4553    0
Name: spam, dtype: int64

In [158]:
#Create bag of words representation using countVectorizer 
v = CountVectorizer() 
X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [147]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59738 stored elements and shape (4457, 7788)>

In [148]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [149]:
X_train_cv.shape

(4457, 7788)

In [150]:
v.get_feature_names_out()[1000]

'anyways'

In [152]:
 v.vocabulary_

{'isn': 3746,
 'frnd': 3006,
 'necesity': 4739,
 'in': 3632,
 'life': 4105,
 'imagine': 3610,
 'urself': 7246,
 'witout': 7580,
 'hw': 3558,
 'feel': 2805,
 'at': 1106,
 'ur': 7233,
 'colleg': 1898,
 'wat': 7427,
 'll': 4166,
 'do': 2378,
 'wth': 7664,
 'cell': 1711,
 'abt': 764,
 'functions': 3036,
 'thnk': 6886,
 'events': 2670,
 'espe': 2651,
 'cared': 1661,
 'missed': 4528,
 'amp': 945,
 'irritated': 3735,
 '4wrd': 533,
 'it': 3751,
 'to': 6960,
 'all': 910,
 'those': 6889,
 'dear': 2196,
 'loving': 4242,
 'frnds': 3007,
 'wthout': 7665,
 'whom': 7526,
 'cant': 1645,
 'live': 4158,
 'jst': 3858,
 'did': 2300,
 'takecare': 6719,
 'goodmorning': 3180,
 'lyricalladie': 4284,
 '21': 356,
 'is': 3739,
 'inviting': 3719,
 'you': 7734,
 'be': 1268,
 'her': 3397,
 'friend': 2998,
 'reply': 5739,
 'yes': 7718,
 '910': 721,
 'or': 4993,
 'no': 4812,
 'see': 6007,
 'www': 7671,
 'sms': 6288,
 'ac': 768,
 'hmmross': 3443,
 'stop': 6518,
 'send': 6033,
 '62468': 580,
 'horrible': 3490,
 'gal': 

In [154]:
X_train_np = X_train_cv.toarray() 
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [155]:
np.where(X_train_np[0]!=0)

(array([ 533,  764,  910,  945, 1106, 1645, 1661, 1711, 1898, 2196, 2300,
        2378, 2651, 2670, 2805, 3006, 3007, 3036, 3180, 3558, 3610, 3632,
        3735, 3746, 3751, 3858, 4105, 4158, 4166, 4242, 4528, 4739, 6719,
        6886, 6889, 6960, 7233, 7246, 7427, 7526, 7580, 7664, 7665]),)

Naive Bayes Classifier

In [157]:
model = MultinomialNB() 
model.fit(X_train_cv, y_train)

MultinomialNB()

In [159]:
y_predict = model.predict(X_test_cv)

In [162]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       977
           1       0.95      0.89      0.92       138

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



Test on  Random Data point 

In [170]:
message = {"🔥CONGRATULATIONS! YOU HAVE WON $10,000 TODAY!!! CLICK NOW!!!"} 
message_cnt = v.transform(message)
model.predict(message_cnt)

array([1])